### ISSUE TITLE
Getting error: Cannot read property 'bindEmitter' of undefined

### ISSUE THREAD

**Issue by shamimmirzai** [aws/aws-xray-sdk-node#125]
Hi.  I've been unable to get X-Ray to work with our nodejs/express application.  As far as I can see I've followed the documentation, but anytime I make a request to the express app, it fails with the following error:

```
Cannot read property 'bindEmitter' of undefined
    at open (/home/ubuntu/bmh/node_modules/aws-xray-sdk-express/lib/express_mw.js:61:12)
    at Layer.handle [as handle_request] (/home/ubuntu/bmh/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/bmh/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/bmh/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/bmh/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/bmh/node_modules/express/lib/router/index.js:275:10)
    at urlencodedParser (/home/ubuntu/bmh/node_modules/body-parser/lib/types/urlencoded.js:88:40)
    at Layer.handle [as handle_request] (/home/ubuntu/bmh/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/bmh/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/bmh/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/bmh/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/bmh/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/ubuntu/bmh/node_modules/body-parser/lib/types/json.js:100:40)
    at Layer.handle [as handle_request] (/home/ubuntu/bmh/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/bmh/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/bmh/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/bmh/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/bmh/node_modules/express/lib/router/index.js:275:10)
...
```

The relevant code in `server.js` is:

```
const loopback = require('loopback')
const boot     = require('loopback-boot')
const app = module.exports = loopback()
var AWSXRay = require('aws-xray-sdk')
AWSXRay.config([
  AWSXRay.plugins.EC2Plugin
])
app.use(AWSXRay.express.openSegment(`transform-${process.env.APP_NAME}`))
app.middleware('routes:after', AWSXRay.express.closeSegment())
```

The `package.json` file is:

```{
  "name": "bmh-transform-loopback",
  "version": "1.0.0",
  "license": "UNLICENSED",
  "main": "server/server.js",
  "scripts": {
    "start": "npm run migrate up && concurrently \"npm run http\" \"npm run sockets\"",
    "lint": "./node_modules/.bin/eslint ./server",
    "dev": "node .",
    "sockets": "ABLY_ON=true PORT=3002 node .",
    "http": "ABLY_ON=false PORT=3000 node .",
    "pretest": "jshint .",
    "posttest": "nsp check",
    "unit-test": "NODE_ENV=test mocha -s 0 --timeout 5000 --reporter nyan spec/**/*$FILE*.spec.js",
    "all-tests": "NODE_ENV=test mocha --timeout 5000 --reporter nyan --recursive 'spec/**/*.spec.js'",
    "console": "./node_modules/.bin/loopback-console",
    "heroku-postbuild": "sh .heroku-postbuild",
    "migrate": "./node_modules/db-migrate/bin/db-migrate -m ./server/migrations"
  },
  "pre-push": [
    "lint"
  ],
  "dependencies": {
    "ably": "1.0.5",
    "apollo-client": "1.7.0",
    "apollo-server-express": "1.3.6",
    "atob": "2.0.3",
    "auth0": "2.3.0",
    "aws-sdk": "2.3.11",
    "aws-xray-sdk": "^2.3.1",
    "bluebird": "^3.5.1",
    "body-parser": "1.15.1",
    "bufferutil": "3.0.2",
    "bugsnag": "^1.9.1",
    "combinations-generator": "1.0.1",
    "compression": "1.0.3",
    "cors": "2.5.2",
    "crypto-js": "^3.1.9-1",
    "csv": "1.1.1",
    "db-migrate-pg": "^0.4.0",
    "dd-trace": "^0.11.0",
    "dotenv-expand": "^4.2.0",
    "es6-promise": "^4.1.1",
    "event-loop-lag": "^1.4.0",
    "exceljs": "1.6.3",
    "express-fileupload": "^0.4.0",
    "express-jwt": "3.4.0",
    "express-request-id": "^1.4.0",
    "formidable": "^1.2.1",
    "googleapis": "19.0.0",
    "graphql": "0.10.5",
    "graphql-server-express": "1.0.0",
    "graphql-subscriptions": "0.4.4",
    "graphql-tools": "1.1.0",
    "heapdump": "^0.3.9",
    "helmet": "0.14.0",
    "html-minifier": "2.1.3",
    "http-proxy": "1.16.2",
    "isomorphic-fetch": "^2.2.1",
    "iterall": "1.1.1",
    "js-base64": "^2.3.2",
    "jsftp": "github:clshortfuse/jsftp#implicit-tls",
    "jsnlog": "2.26.2",
    "json-stringify-safe": "5.0.1",
    "jsrsasign": "~4.8.3",
    "kue": "0.11.5",
    "layer-api": "2.3.2",
    "layer-patch": "1.0.0",
    "limiter": "^1.1.4",
    "lodash": "4.17.4",
    "loopback": "3.24.0",
    "loopback-boot": "^2.27.1",
    "loopback-component-explorer": "^6.0.0",
    "loopback-component-storage": "^3.3.1",
    "loopback-connector-postgresql": "^3.3.0",
    "loopback-console": "1.1.0",
    "loopback-context": "^3.3.0",
    "loopback-jwt": "1.0.1",
    "moment": "2.14.0",
    "moment-range": "^4.0.1",
    "moment-timezone": "0.5.4",
    "multer": "1.3.0",
    "needle": "1.0.0",
    "node-dir": "0.1.17",
    "node-uuid": "1.4.7",
    "oauth-1.0a": "^2.2.4",
    "papaparse": "^4.5.0",
    "pg-boss": "^2.5.1",
    "pg-native": "^3.0.0",
    "pm2": "2.10.4",
    "promise-throttle": "1.0.0",
    "q": "1.4.1",
    "randomstring": "1.1.5",
    "request": "2.73.0",
    "request-promise": "4.2.2",
    "rimraf": "2.6.1",
    "sendwithus": "3.0.0",
    "serve-favicon": "2.0.1",
    "socket.io": "1.4.5",
    "source-map-loader": "0.1.5",
    "strong-error-handler": "^1.0.1",
    "subscriptions-transport-ws": "0.7.3",
    "superagent": "2.0.0",
    "supertest": "^3.0.0",
    "tokenbucket": "0.3.2",
    "trycatch": "1.5.21",
    "underscore": "1.8.3",
    "url-parse": "1.1.8",
    "utf-8-validate": "3.0.3",
    "uuid": "^3.2.1",
    "winston": "2.2.0",
    "ws": "3.0.0",
    "xkcd-password": "2.0.0",
    "xml-parser": "1.2.1",
    "xml2js": "0.4.17"
  },
  "devDependencies": {
    "babel-preset-es2015": "6.6.0",
    "chai": "*",
    "chai-as-promised": "^7.1.1",
    "chai-sorted": "^0.2.0",
    "chai-subset": "^1.6.0",
    "chai-things": "^0.2.0",
    "concurrently": "^4.1.0",
    "db-migrate": "^0.11.1",
    "dotenv": "4.0.0",
    "eslint": "^4.19.1",
    "faker": "^4.1.0",
    "jshint": "2.5.6",
    "mocha": "*",
    "nock": "^10.0.6",
    "nsp": "2.1.0",
    "pre-push": "^0.1.1"
  },
  "engines": {
    "node": "8.x.x",
    "yarn": "1.x.x"
  },
  "cacheDirectories": [
    "client/node_modules",
    "node_modules"
  ],
  "repository": {
    "type": "",
    "url": ""
  },
  "description": "bmh-transform-loopback"
}
```

Any assistance would be appreciated.  Thanks

**Comment by chrisradek** [comment]
@shamdsc 
The code sample you provided looks like it should work assuming that's just your boilerplate.

I recently created #124 which tests the X-Ray SDK in an express app. The logic to actually create the app is very similar to what you've got: [link](https://github.com/aws/aws-xray-sdk-node/pull/124/files#diff-001aba8211f5fce0dd0ca087443ac436R15)

I modified [this line](https://github.com/aws/aws-xray-sdk-node/pull/124/files#diff-001aba8211f5fce0dd0ca087443ac436R4) to require `loopback` instead of `express`, and also added `loopback-boot`, but the tests are still passing.

Can you provide a more complete code sample that reproduces this issue?

**Comment by chrisradek** [comment]
@shamdsc 
Also, do you happen to be using any modules that work with `continuation-local-storage`? The error you're getting indicates that the SDK's context in `continuation-local-storage` isn't available when the `openSegment` middleware is called, so I'm wondering if maybe another dependency is doing something that clears that context out.

**Comment by chrisradek** [comment]
I suspect this is related to #111. Can you also check if `cls-hooked` exists in your `node_modules` directory? If so, can you try installing the `experimental` branch of the x-ray SDK?

> npm install --save aws-xray-sdk@experimental

**Comment by shamdsc** [comment]
@chrisradek many thanks for all your comments and assistance 🙏🏻.  Using the experimental branch seems to eliminate the error.  Much appreciated.  Is there any way for me to be notified once those changes make it into the mainstream package?

**Comment by MahmoudMH** [comment]
Same Error here, Even I run this code `npm install --save aws-xray-sdk@experimental`

The problem hasn't resolved, this is what I got after running the above command
"aws-xray-sdk": "^2.3.5-experimental.1".

Any help?

**Comment by willarmiros** [comment]
@MahmoudMH could you give some more details about your problem? What environment are you running your application from - locally, lambda, etc? And Can I have some sample code to reproduce your error?
