### ISSUE TITLE
Support Pool from pg

### ISSUE THREAD

**Issue by nmaves** [aws/aws-xray-sdk-node#250]
Does this library support using a connection pool from the PG library?

It seems to error out on me when I use a pool but not when I use a connection.

**Comment by willarmiros** [comment]
Hi @nmaves,

We do support capturing pool connections, as long as they're made with an instrumented `pg` client. Please see example code [here](https://github.com/aws/aws-xray-sdk-node/tree/master/packages/postgres#automatic-mode-example).

**Comment by nmaves** [comment]
Ah, so you don't support the following correct?

```
pool.query(callback: (err?: Error, result: pg.Result)) => void
```

**Comment by nmaves** [comment]
I am still having issues,  this must be something simple I am missing.

```
import AWSXRay from 'aws-xray-sdk'
import * as pg from 'pg'

const postgres = AWSXRay.capturePostgres(pg)

const { Pool } = postgres

export const getConnectionPool = env => {
  // Create Postgres connection pool
  const user = process.env.RO_USERNAME || env['ro_username']
  const host = process.env.RO_HOST || env['ro_host']
  const password = process.env.RO_PASSWORD || env['ro_password']
  const database = process.env.RO_DATABASE || env['ro_database']
  const port = process.env.RO_PORT || env['ro_port']

  return new Pool({
    user,
    host,
    password,
    database,
    port,
    max: 50, // max active connections
  })
}
```

then later

```
const client = await pool.connect()
const { rows } = await client.query(patronFetchByAuthTokenQuery, [token])
client.release()
```

```
stacktrace: ["Error: Context creation failed: Failed to get the current sub/segment from the context.",…]
0: "Error: Context creation failed: Failed to get the current sub/segment from the context."
1: "    at Object.contextMissingRuntimeError [as contextMissing] (/Users/nmaves/projects/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)"
2: "    at Object.getSegment (/Users/nmaves/projects/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)"
3: "    at Object.resolveSegment (/Users/nmaves/projects/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)"
4: "    at Client.query (/Users/nmaves/projects/node_modules/aws-xray-sdk-postgres/lib/postgres_p.js:56:24)"
5: "    at createContext (/Users/nmaves/projects/src/index.js:117:37)"
6: "    at process._tickCallback (internal/process/next_tick.js:68:7)"
```

**Comment by willarmiros** [comment]
This depends on a few questions:
* Are you operating in a Lambda environment something else? 
* Are you using the Express web framework?
* What version of the SDK are you using?

In general, you need to have a segment available before you can automatically capture postgres calls. This happens by default in Lambda, but you may need to create your own in other environments.

**Comment by nmaves** [comment]
First off thanks for the help, I really appreciate it.

Yes, we are using an express server with apollo graphql.  We are using the pool passed down to our Dataloader instances with the graphql context.

"aws-xray-sdk": "^2.5.0"

```
getEnvironmentParams()
  .then(async env => {

    const pool = await getConnectionPool(env)
    const elasticsearch = getTitlesClient(env, metrics)
    const memcache = getMemcacheClient(env)

    app.use(AWSXRay.express.openSegment('HooplaGraphql'))
    
    const server = new ApolloServer({
      ...
      context: async ({ req }) => await createContext(req, pool, memcache, elasticsearch),
      ...
    })

    server.applyMiddleware({ app, path: '/graphql' })

    app.use(AWSXRay.express.closeSegment())

    app.listen({ port }, () => console.log(`🚀 Server ready at http://localhost:${port}${server.graphqlPath}`))
  })
  .catch(error => {
    ...
  })
```

**Comment by nmaves** [comment]
@willarmiros I have been trying to debug this all day.  I did stumble upon this from the PG Pool

```javascript
class Pool extends EventEmitter {
  constructor (options, Client) {
    super()
    this.options = Object.assign({}, options)
    this.options.max = this.options.max || this.options.poolSize || 10
    this.log = this.options.log || function () { }
    this.Client = this.options.Client || Client || require('pg').Client
    this.Promise = this.options.Promise || global.Promise

    if (typeof this.options.idleTimeoutMillis === 'undefined') {
      this.options.idleTimeoutMillis = 10000
    }

    this._clients = []
    this._idle = []
    this._pendingQueue = []
    this._endCallback = undefined
    this.ending = false
    this.ended = false
  }
```

So we should be able to use `pool.query()` with the following configuration.

```javascript
import AWSXRay from 'aws-xray-sdk'

const pg = AWSXRay.capturePostgres(require('pg'))

  // Create Postgres connection pool
  const user = process.env.RO_USERNAME || env['ro_username']
  const host = process.env.RO_HOST || env['ro_host']
  const password = process.env.RO_PASSWORD || env['ro_password']
  const database = process.env.RO_DATABASE || env['ro_database']
  const port = process.env.RO_PORT || env['ro_port']

  return new pg.Pool({
    user,
    host,
    password,
    database,
    port,
    max: 50, // max active connections,
    Client: pg.Client
  })

```

**Comment by nmaves** [comment]
Are there any known race conditions with the automatic setup with express?


You can see from my logs that an Express segment is getting created and then blowing up because there is no segment.....

```
2020-02-10 14:39:56.155 -07:00 [DEBUG] Starting express segment: { url: /graphql, name: TestApp, trace_id: 1-5e41cdac-9b277ed99a900e3f4c18935b, id: e11e83d574287144, sampled: true }
token 2c1c7b0b-1b43-416c-ae0f-dd19d17685d0
2020-02-10 14:39:56.380 -07:00 [INFO] Successfully refreshed centralized sampling rule cache.
/Users/nmaves/projects/node_modules/aws-xray-sdk-core/lib/context_utils.js:21
        throw new Error(message);
        ^

Error: Failed to get the current sub/segment from the context.
    at Object.contextMissingRuntimeError [as contextMissing] (/Users/nmaves/projects/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)
    at Object.getSegment (/Users/nmaves/projects/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
    at Object.resolveSegment (/Users/nmaves/projects/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
    at Client.captureQuery [as query] (/Users/nmaves/projects/node_modules/aws-xray-sdk-postgres/lib/postgres_p.js:56:24)
    at PendingItem.connect [as callback] (/Users/nmaves/projects/node_modules/pg-pool/index.js:342:14)
    at Pool._acquireClient (/Users/nmaves/projects/node_modules/pg-pool/index.js:271:21)
    at Pool._pulseQueue (/Users/nmaves/projects/node_modules/pg-pool/index.js:123:19)
    at process.nextTick (/Users/nmaves/projects/node_modules/pg-pool/index.js:159:37)
    at /Users/nmaves/projects/node_modules/async-listener/glue.js:188:31
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by awssandra** [comment]
Hi nmaves,

Sorry for the issue! Would you mind posting a code snippet showing the usage? Also, are you running on a container or EC2 or Lambda?

There are no known context issues open about this today, but happy to deep dive into it.

**Comment by willarmiros** [comment]
Hi @nmaves,

Thanks for the further information. It's possible there is an issue with the context getting overwritten. What does your `createContext` function do? In the `aws-xray-sdk`, we use `continuation-local-storage` (although this is changing to be `cls-hooked` in 3.0.0) to maintain a namespace with a key-value pair representing segment context in automatic mode. See [context_utils.js](https://github.com/aws/aws-xray-sdk-node/blob/master/packages/core/lib/context_utils.js).

So it is possible that we create that segment and Apollo's context somehow overwrites or erases it?

**Comment by nmaves** [comment]
This was all around cls.  Once I upgraded to the lastest version with cls-hooked is all worked perfect.
