### ISSUE TITLE
 Error: Failed to get the current sub/segment from the context.

### ISSUE THREAD

**Issue by MatteoGioioso** [aws/aws-xray-sdk-node#258]
I am trying to run a the x-ray daemon inside a docker container

this is my `docker-compose.yaml`

```
version: '3'

services:
//Other services

  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 8080:8080
    links:
      - redis
    depends_on:
      - db
    command:
      sh -c 'npm i && npm run start'

  xray:
    build:
      context: ./
      dockerfile: Dockerfile.xray
    ports:
    - 2000:2000/udp
    - 2000:2000/tcp
    environment:
      - AWS_REGION=ap-southeast-1

```

Docker file for the xray daemon image

```
FROM amazonlinux
RUN yum install -y unzip
RUN curl -o daemon.zip https://s3.dualstack.us-east-2.amazonaws.com/aws-xray-assets.us-east-2/xray-daemon/aws-xray-daemon-linux-3.x.zip
RUN unzip daemon.zip && cp xray /usr/bin/xray
ENTRYPOINT ["/usr/bin/xray", "-t", "0.0.0.0:2000", "-b", "0.0.0.0:2000"]
EXPOSE 2000/udp
EXPOSE 2000/tcp
```

my instrumented nodejs app
```
const AWSXRay = require('aws-xray-sdk')
AWSXRay.config([AWSXRay.plugins.EC2Plugin])
AWSXRay.setDaemonAddress('http://xray:2000')

app.use(AWSXRay.express.openSegment('my-backend'))
// all the routes here
// ...

app.use(AWSXRay.express.closeSegment())
```

Those are the docker-compose logs

```
xray_1   | 2020-03-03T06:16:28Z [Info] Initializing AWS X-Ray daemon 3.2.0
xray_1   | 2020-03-03T06:16:28Z [Info] Using buffer memory limit of 9 MB
xray_1   | 2020-03-03T06:16:28Z [Info] 144 segment buffers allocated
xray_1   | 2020-03-03T06:16:28Z [Info] Using region: ap-southeast-1

xray_1   | 2020-03-03T06:30:27Z [Info] HTTP Proxy server using X-Ray Endpoint : https://xray.ap-southeast-1.amazonaws.com
xray_1   | 2020-03-03T06:30:27Z [Info] Starting proxy http server on 0.0.0.0:2000

```

I have a IAM role attached to my EC2 with `AWSXrayFullAccess` policy.
And this is the error I got while send a request to my app:

```
 Error: Failed to get the current sub/segment from the context.
app_1    |     at Object.contextMissingRuntimeError [as contextMissing] (/var/www/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)
app_1    |     at Object.getSegment (/var/www/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
app_1    |     at Object.resolveSegment (/var/www/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
app_1    |     at close (/var/www/app/node_modules/aws-xray-sdk-express/lib/express_mw.js:95:29)
app_1    |     at Layer.handle_error (/var/www/app/node_modules/express/lib/router/layer.js:71:5)
app_1    |     at trim_prefix (/var/www/app/node_modules/express/lib/router/index.js:315:13)
app_1    |     at /var/www/app/node_modules/express/lib/router/index.js:284:7
app_1    |     at Function.process_params (/var/www/app/node_modules/express/lib/router/index.js:335:12)
app_1    |     at Domain.next (/var/www/app/node_modules/express/lib/router/index.js:275:10)
app_1    |     at Domain.emit (events.js:198:13)
app_1    |     at Domain.EventEmitter.emit (domain.js:448:20)
app_1    |     at Domain._errorHandler (domain.js:246:21)
app_1    |     at Object.setUncaughtExceptionCaptureCallback [as captureFn] (domain.js:145:29)
app_1    |     at process._fatalException (internal/bootstrap/node.js:496:31)
app_1    |     at process._asyncFatalException [as _fatalException] (/var/www/app/node_modules/async-listener/glue.js:211:34)

```

Upon reading the instructions I have set the `AWS_XRAY_CONTEXT_MISSING=LOG_ERROR`,
but I got another error now:

```
RangeError [ERR_SOCKET_BAD_PORT]: Port should be >= 0 and < 65536. Received 0.
app_1    |     at Socket.send (dgram.js:385:11)
app_1    |     at Object.send (/var/www/app/node_modules/aws-xray-sdk-core/lib/segment_emitter.js:136:12)
app_1    |     at Segment.flush (/var/www/app/node_modules/aws-xray-sdk-core/lib/segments/segment.js:361:20)
app_1    |     at Segment.close (/var/www/app/node_modules/aws-xray-sdk-core/lib/segments/segment.js:343:10)
app_1    |     at ServerResponse.endSegment (/var/www/app/node_modules/aws-xray-sdk-express/lib/express_mw.js:61:17)
app_1    |     at ServerResponse.emit (events.js:203:15)
app_1    |     at ServerResponse.EventEmitter.emit (domain.js:466:23)
app_1    |     at ServerResponse.emitted (/var/www/app/node_modules/emitter-listener/listener.js:134:21)
app_1    |     at onFinish (_http_outgoing.js:671:10)
app_1    |     at /var/www/app/node_modules/async-listener/glue.js:188:31
app_1    |     at process._tickCallback (internal/process/next_tick.js:61:11)
```

At this point I got kind of stuck. Sorry if I have missed something.

Thanks

```
node: v10.19.0
aws-xray-sdk: 2.5.0
express: 4.17.1
AMI: amzn2-ami-hvm-2.0.20200207.1-x86_64-gp2 (ami-0f02b24005e4aec36)
```

**Comment by MatteoGioioso** [comment]
Ok, upon digging the sdk source code I just realized that I should just use `xay:200` instead `http://xray:2000`.

Sorry
