### ISSUE TITLE
How should X-Ray behave when no incoming context is available?

### ISSUE THREAD

**Issue by vdeturckheim** [aws/aws-xray-sdk-node#325]
Hey there,

I am investigating https://github.com/aws/aws-xray-sdk-node/issues/324 after a ping from @JeremieDoctrine.
I am trying to setup a minimal test bench but for some reason, aws-xray-sdk@3.1.0 does not let me to perform outgoing HTTP requests out of the blue.

For instance:
```js
const Wreck = require('@hapi/wreck');
Wreck.get('https://amazon.com/', {})
    .then((res) => {

        console.log('res', !!res);
    })
    .catch((err) => {

        console.log(err);
    });
```
returns
```
res true
```
while
```js
const AWSXRay = require('aws-xray-sdk');
const AWS = AWSXRay.captureAWS(require('aws-sdk'));
AWS.config.update({region: process.env.DEFAULT_AWS_REGION || 'us-west-2'});

AWSXRay.captureHTTPsGlobal(require('https'));

const Wreck = require('@hapi/wreck');
Wreck.get('https://amazon.com/', {})
    .then((res) => {

        console.log('res', !!res);
    })
    .catch((err) => {

        console.log(err);
    });
```
returns
```
Error: Failed to get the current sub/segment from the context.
    at Object.contextMissingRuntimeError [as contextMissing] (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)
    at Object.getSegment (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
    at Object.resolveSegment (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
    at captureOutgoingHTTPs (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/node_modules/aws-xray-sdk-core/lib/patchers/http_p.js:95:31)
    at Object.captureHTTPsRequest [as request] (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/node_modules/aws-xray-sdk-core/lib/patchers/http_p.js:189:12)
    at internals.Client._request (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/node_modules/@hapi/wreck/lib/index.js:181:28)
    at internals.Client.request (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/node_modules/@hapi/wreck/lib/index.js:75:26)
    at internals.Client._shortcut (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/node_modules/@hapi/wreck/lib/index.js:522:32)
    at internals.Client.get (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/node_modules/@hapi/wreck/lib/index.js:497:21)
    at Object.<anonymous> (/Users/vdeturckheim/tmp/aws-xray-sdk-node-sample/con.js:8:7)
```
Am I missing something in the setup of `aws-xray-sdk`? I used the sample app as a starting point.

Thanks a lot!

**Comment by lupengamzn** [comment]
Hi @vdeturckheim ,

Currently we don't have a middleware for Wreck and you may have to manually create a segment for your downstream services so that the downstream subsegment generated can find its parent segment.

You can try:

```js
var segment = new AWSXRay.Segment('Test');
var ns = AWSXRay.getNamespace();

ns.run(function () {
  AWSXRay.setSegment(segment);
  
  // Your code
  const Wreck = require('@hapi/wreck');
  Wreck.get('https://amazon.com/', {})
    .then((res) => {

        console.log('res', !!res);
    })
    .catch((err) => {

        console.log(err);
    });
  
  segment.close();
});
```
For more information, please take reference to [here](https://github.com/aws/aws-xray-sdk-node/blob/62605b8882b3a5b9a65456bf19fbc9713bbe8802/packages/core/README.md#developing-custom-solutions-without-middleware)

**Comment by vdeturckheim** [comment]
@lupengamzn thanks for the answer!

This is a bit complex: I have an agent my users use, it is similar to X-Ray but focus on security. It has to connect to our backends from time to time outside the context of an incoming request. I actually met this issue in the init phase of my agent when it tries to connect to our backends for the first time.

Having to wrap it in a context for X-Ray is probably something I'd prefer to avoid as it would require me to depend on X-Ray for my agent.
All other APMs agents (at least New Relic, Elastic and pm2) work in such setups. 

Also, alternatively, there could be context loss in some cases when using the cls-hooked (or even the [API provided in Node.js core](https://nodejs.org/dist/latest-v12.x/docs/api/async_hooks.html#async_hooks_class_asynclocalstorage)). Most tools using cls-like APIs usualu fail-safe on such cases.

**Comment by rrrix** [comment]
@vdeturckheim I opted to just turn off the "Context Missing" error altogether like this:

```typescript
AWSXRay.setContextMissingStrategy(() => undefined);
```

The AWS X-Ray SDK (`RUNTIME_ERROR` and `LOG_ERROR`) assumes that there will *always* be an open Segment, which would require basically monkey-patching every single library that anyone could possibly use :)

**Comment by vdeturckheim** [comment]
@rrrix thanks a lot, make sense!
