### ISSUE TITLE
Getting "Error: Failed to get the current sub/segment from the context during" testing after upgrading to 3.1.0

### ISSUE THREAD

**Issue by aaleksandrov** [aws/aws-xray-sdk-node#326]
Hi, I am getting the error 
```
2020-08-18 17:07:51.359 +02:00 [ERROR] Error: Failed to get the current sub/segment from the context.
    at Object.contextMissingLogError [as contextMissing] (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/aws-xray-sdk-core/lib/context_utils.js:26:19)
    at Object.getSegment (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
    at Object.resolveSegment (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
    at features.constructor.captureAWSRequest [as customRequestHandler] (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:60:29)
    at features.constructor.addAllRequestListeners (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/aws-sdk/lib/service.js:279:34)
    at features.constructor.makeRequest (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/aws-sdk/lib/service.js:203:10)
    at features.constructor.svc.(anonymous function) [as putRecord] (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/aws-sdk/lib/service.js:674:23)
    at Promise.try (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/src/services/KinesisPublisher.ts:39:32)
    at tryCatcher (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/bluebird/js/release/method.js:39:29)
    at KinesisPublisher.publish (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/src/services/KinesisPublisher.ts:25:27)
    at ResourceController.ingest (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/src/controller/v1/ResourceController.ts:38:34)
    at InversifyExpressServer.<anonymous> (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/inversify-express-utils/lib/server.js:156:119)
    at step (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/inversify-express-utils/lib/server.js:32:23)
    at Object.next (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/inversify-express-utils/lib/server.js:13:53)
    at fulfilled (/home/alexey.aleksandrov/work/fridge-serverless-stream-ingester/node_modules/inversify-express-utils/lib/server.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
.......
```
while running tests using xray-sdk 3.1.0
I have `AWS_XRAY_CONTEXT_MISSING=LOG_ERROR`  set but it doesn't seems to affect the error . We recently upgraded `xray-sdk` from 1.x to 3. When using version 1 we had no such issue

This env variable is successfully passed to handler.

Can you help me with this?

We use `express` + `serverless-http` + `serverless-offline` for running tests
test runner 
```
AWS_XRAY_CONTEXT_MISSING=LOG_ERROR ENVIRONMENT=test ./node_modules/.bin/serverless offline -c --environment=environments/test.yml start --exec='yarn mocha --opts tests/mocha.opts ./tests/integration/**/*Spec.js"
```

Update: setting `AWS_XRAY_LOG_LEVEL=silent` removes the error but I am not sure that silencing ALL logs for X-Ray is a proper solution in this case

**Comment by wangzlei** [comment]
Hi,
Could you share the full track stack? It can help discover the source of problem.

Thanks.

**Comment by aaleksandrov** [comment]
Hi @wangzlei , I updated the trace

**Comment by wangzlei** [comment]
If the ERROR happens only in test, suppressing it by `AWS_XRAY_LOG_LEVEL=silent` is the proper way. The ERROR is caused by X-Ray is uninitialized in testing. X-Ray SDK 1.X does not show this error log but we add this log from 3.1 so you will get this error after upgrading.

We will also have a feature of turning off X-Ray in Node, users can turn off X-Ray function in their tests by setting an environment variable. https://github.com/aws/aws-xray-sdk-node/issues/231

**Comment by aaleksandrov** [comment]
thank you @wangzlei for clarification, then I'll disable logs and close the issue
