### ISSUE TITLE
capturePostgres send back TypeError: Cannot read property 'name' of undefined 

### ISSUE THREAD

**Issue by gchablowski** [aws/aws-xray-sdk-node#38]
I tried to use x-ray with pg in a lambda function. I use pg with promise. I tried different thinks, like add AWSXRay.capturePromise(), but I always get the following error:

`TypeError: Cannot read property 'name' of undefined
    at createSqlData (/var/task/node_modules/aws-xray-sdk-postgres/lib/postgres_p.js:90:25)
    at Client.captureQuery [as query] (/var/task/node_modules/aws-xray-sdk-postgres/lib/postgres_p.js:44:27)
    at connect (/var/task/node_modules/pg-pool/index.js:256:14)
    at client.connect (/var/task/node_modules/pg-pool/index.js:227:11)
    at Connection.<anonymous> (/var/task/node_modules/pg/lib/client.js:150:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:121:20)
    at Connection.emit (events.js:211:7)
    at Socket.<anonymous> (/var/task/node_modules/pg/lib/connection.js:123:12)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread [as _originalOnread] (net.js:607:20)
    at TCP.onread (/var/task/node_modules/async-listener/glue.js:188:31)`

As I understand it the capturePostgres never capture the query that I send.
I think I have followed the documentation. I suppose it's a bug, but not sure of the where ?
You can acces my code here : https://github.com/Back9digital/node_lib/blob/x-ray/lib/db/postgresql.js

Thanks

**Comment by gchablowski** [comment]
Hi,

We use 7.4.3.
I suppose that it can be link to the problem you have already. But seem like a new bug. Don't really match the other. 

Thanks

**Comment by haotianw465** [comment]
Yes we already know a few issues with latest promise based `pg`. The current postgres capture is `EventListener` based and it is not promise-aware. This is in our backlog and we will try our best to get the support out as soon as possible. 

Right now I'm closing this one in favor of this https://github.com/aws/aws-xray-sdk-node/issues/34 so we have a centralized place to track all issues and progress. Feel free to leave any additional comments on that issue.
