### ISSUE TITLE
TypeError "aws_xray_sdk_mysql_1.captureMySQL is not a function"

### ISSUE THREAD

**Issue by richardcornelissen** [aws/aws-xray-sdk-node#450]
We've recently updated `aws-xray-sdk-mysql` from version `3.2.0` to `3.3.3`, but experienced issues with our Typescript projects.

Due to the changed Typescript definitions, we had to adjust the import from
```typescript
import captureMySQL from 'aws-xray-sdk-mysql';
```

to

```typescript
import {captureMySQL} from 'aws-xray-sdk-mysql';
```

However, this resulted in errors as such:
```log
{
    "errorType": "TypeError",
    "errorMessage": "aws_xray_sdk_mysql_1.captureMySQL is not a function",
    "stack": [
        "TypeError: aws_xray_sdk_mysql_1.captureMySQL is not a function",
        "    at Object.exports.setup (/var/task/src/api.js:2:1851104)",
        "    at Object.<anonymous> (/var/task/src/api.js:2:1848725)",
        "    at __webpack_require__ (/var/task/src/api.js:2:295)",
        "    at Object.<anonymous> (/var/task/src/api.js:2:1847607)",
        "    at __webpack_require__ (/var/task/src/api.js:2:295)",
        "    at /var/task/src/api.js:2:1594",
        "    at Object.<anonymous> (/var/task/src/api.js:2:1641)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)"
    ]
}
```

**Workaround**

As a temporary workaround, replace

```typescript
import {captureMySQL} from 'aws-xray-sdk-mysql';
```

With

```typescript
// eslint-disable-next-line @typescript-eslint/no-var-requires
const captureMySQL = require('aws-xray-sdk-mysql');
```

**Comment by willarmiros** [comment]
Hi @richardcornelissen,

I wasn't able to reproduce this with a normal TypeScript app importing `captureMySQL` normally. I noticed you're using webpack, so I think it's likely related to some of the magic that does under the hood. Thank you for providing the workaround, there are some known issues with this SDK and webpack so I will label this as a bug within that category for now.

**Comment by beanaroo** [comment]
Can confirm that we are getting the same issue:
```
capturePostgres is not a function
```

**Comment by Irvel** [comment]
Hi @willarmiros, we're encountering the same issue when importing 'aws-xray-sdk-postgres'. The proposed workaround in the initial post worked for us. 

For context, we are not using webpack. We stumbled upon the issue while replacing the 'aws-xray-sdk' package with 'aws-xray-sdk-core' + 'aws-xray-sdk-postgres'

**Comment by Ibessas** [comment]
Using 
```
var AWSXRay = require('aws-xray-sdk');
AWSXRay.captureMySQL(require('mysql2'));
```
as is said in the documentation on the Lambda Example, is not working either, with the error: 
`{"errorType":"TypeError","errorMessage":"AWSXRay.captureMySQL is not a function","stack":["TypeError: AWSXRay.captureMySQL is not a function"," at Object.<anonymous> (/var/task/index.js:3:9)"," at Module._compile (internal/modules/cjs/loader.js:999:30)"," at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)"," at Module.load (internal/modules/cjs/loader.js:863:32)"," at Function.Module._load (internal/modules/cjs/loader.js:708:14)"," at Module.require (internal/modules/cjs/loader.js:887:19)"," at require (internal/modules/cjs/helpers.js:74:18)"," at _tryRequire (/var/runtime/UserFunction.js:75:12)"," at _loadUserApp (/var/runtime/UserFunction.js:95:12)"," at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)"]}`

**Comment by willarmiros** [comment]
Hi @Irvel thanks for reporting as well. We've documented this issue and will investigate a fix when we have bandwidth. For what it's worth here is where we define the `capturePostgres` function type: https://github.com/aws/aws-xray-sdk-node/blob/91b7f65565e863e5c7cd4c6c10578ae3ab404982/packages/postgres/lib/postgres_p.d.ts#L4

I wasn't able to reproduce initially so this will require a longer look. As a side note, the [AWS Distro for OpenTelemetry JavaScript](https://aws-otel.github.io/docs/getting-started/js-sdk/trace-manual-instr) has support for instrumenting MySQL and Postgres functions and is written in native TypeScript for much more robust typings. It also has first-class support for tracing with X-Ray, so feel free to check that out.

**Comment by paya-cz** [comment]
I have the same issue with `capturePostgres` function. I believe this should fix the issue in the typings file:

```ts
export default function captureMySQL(mysql: typeof MySQL): captureMySQL.PatchedMySQL;
```

instead of the current:
https://github.com/aws/aws-xray-sdk-node/blob/58737b4bec258331ec7aba30cd3f006a19341315/packages/mysql/lib/mysql_p.d.ts#L4

Same fix should apply to the postgres version.
