### ISSUE TITLE
`aws-xray-sdk-postgres` does not work with `pg-copy-streams`

### ISSUE THREAD

**Issue by paya-cz** [aws/aws-xray-sdk-node#478]
I use [pg-copy-streams](https://github.com/brianc/node-pg-copy-streams) to stream CSV to a table, just like in the [STDIN example](https://github.com/brianc/node-pg-copy-streams#pipe-from-a-file-to-table-copyin---copy-from). XRay-instrumented `pg.Client` will crash when used with `pg-copy-streams`:

-----

**type**: TypeError
**message**: cb is not a function

**stack**:
TypeError: cb is not a function
    at Query.args.callback (/app/node_modules/aws-xray-sdk-postgres/lib/postgres_p.js:88:9)
    at Query.handleReadyForQuery (/app/node_modules/pg/lib/query.js:138:12)
    at Client._handleReadyForQuery (/app/node_modules/pg/lib/client.js:290:19)
    at Connection.emit (events.js:400:28)
    at /app/node_modules/pg/lib/connection.js:114:12
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:104:9)
    at TLSSocket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at TLSSocket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)"

-----
aws-xray-sdk-core: v3.3.4
aws-xray-sdk-postgres: v3.3.4

**Comment by willarmiros** [comment]
Hi @paya-cz,

Thanks for raising this, seems like a small bug in our postgres patcher where we're not checking if it's a function here, if you're open to make a quick PR + unit test: https://github.com/aws/aws-xray-sdk-node/blob/58737b4bec258331ec7aba30cd3f006a19341315/packages/postgres/lib/postgres_p.js#L72

If you need an immediate alternative, I would recommend checking out the [AWS Distro for OpenTelemetry JS](https://aws-otel.github.io/docs/getting-started/js-sdk/trace-manual-instr), which supports instrumenting many more JS libraries than this SDK including Postgres, and it has first-class support for AWS X-Ray.
