### ISSUE TITLE
Support undici

### ISSUE THREAD

**Issue by tenjaa** [aws/aws-xray-sdk-node#622]
[Undici](https://github.com/nodejs/undici) is the new official node http client.
When trying xray on a Node-18-Lambda while using undici I get the following error

```
import {captureHTTPsGlobal} from 'aws-xray-sdk';
import * as http from 'http';
import * as https from 'https';

captureHTTPsGlobal(http);
captureHTTPsGlobal(https);
```
```
2023-10-22T11:24:52.170Z	undefined	ERROR	Uncaught Exception 	{
    "errorType": "TypeError",
    "errorMessage": "Cannot add property __request, object is not extensible",
    "stack": [
        "TypeError: Cannot add property __request, object is not extensible",
        "    at enableCapture (file:///var/task/index.mjs:34012:25)",
        "    at captureHTTPsGlobal3 (file:///var/task/index.mjs:33900:9)",
        "    at file:///var/task/index.mjs:35587:44",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"
    ]
}

```

**Comment by wangzlei** [comment]
undici support is in X-Ray nodejs SDK backlog, but we don't have specific timeline due to resource constrains. Now xray service is able to work with OpenTelemetry, for customers need new libraries support at the moment, we recommend customers onboard [opentelemetry](https://aws-otel.github.io/docs/getting-started/javascript-sdk)
Refer to OpenTelemetry undici support: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1021
