### ISSUE TITLE
Restify - sub/segment error

### ISSUE THREAD

**Issue by scandinaro** [aws/aws-xray-sdk-node#78]
When trying to use restify and the dynamodb document client I get the following sub/segment error 

```
Error: Failed to get the current sub/segment from the context.
    at Object.contextMissingRuntimeError [as contextMissing] (/Users/dominicscandinaro/Projects/api/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)
    at Object.getSegment (/Users/dominicscandinaro/Projects/api/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
    at Object.resolveSegment (/Users/dominicscandinaro/Projects/api/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
    at features.constructor.captureAWSRequest [as customRequestHandler] (/Users/dominicscandinaro/Projects/api/node_modules/aws-xray-sdk-core/lib/patchers/aws_p.js:60:29)
    at features.constructor.addAllRequestListeners (/Users/dominicscandinaro/Projects/api/node_modules/aws-sdk/lib/service.js:283:12)
    at features.constructor.makeRequest (/Users/dominicscandinaro/Projects/api/node_modules/aws-sdk/lib/service.js:203:10)
    at features.constructor.svc.(anonymous function) [as getItem] (/Users/dominicscandinaro/Projects/api/node_modules/aws-sdk/lib/service.js:642:23)
    at DocumentClient.get (/Users/dominicscandinaro/Projects/api/node_modules/aws-sdk/lib/dynamodb/document_client.js:265:32)
    at DocumentClient.dynamoDb.get (/Users/dominicscandinaro/Projects/api/lgs-lib/lib/dynamoDb.js:22:19)
    at Object.get (/Users/dominicscandinaro/Projects/api/lgs-lib/lib/cart.js:9:37)
    at Server.Cart.server.get (/Users/dominicscandinaro/Projects/api/routes/cart.js:11:38)
    at next (/Users/dominicscandinaro/Projects/api/node_modules/restify/lib/server.js:912:30)
    at f (/Users/dominicscandinaro/Projects/api/node_modules/restify/node_modules/once/once.js:25:25)
    at Server.Auth (/Users/dominicscandinaro/Projects/api/lib/auth.js:261:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at process.fallback (/Users/dominicscandinaro/Projects/api/node_modules/async-listener/index.js:565:15)
Failed to get the current sub/segment from the context. RequestError: Failed to get the current sub/segment from the context.
    at Object.get (/Users/dominicscandinaro/Projects/api/lgs-lib/lib/favorite.js:24:15)
    at getFavorite (/Users/dominicscandinaro/Projects/api/routes/favorites.js:7:38)
    at Server.Favorites.server.get (/Users/dominicscandinaro/Projects/api/routes/favorites.js:59:15)
    at next (/Users/dominicscandinaro/Projects/api/node_modules/restify/lib/server.js:912:30)
    at f (/Users/dominicscandinaro/Projects/api/node_modules/restify/node_modules/once/once.js:25:25)
    at Server.Auth (/Users/dominicscandinaro/Projects/api/lib/auth.js:261:21)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    at process.fallback (/Users/dominicscandinaro/Projects/api/node_modules/async-listener/index.js:565:15)
```

**My restify app.js code:**
```javascript
const env     = process.env.NODE_ENV || 'local';
const config  = require('./env')
const restify = require('restify');
const xray    = require('aws-xray-sdk-restify');
const routes  = require('./routes');
const server  = restify.createServer({ name: 'api' });

// Enable x-ray
xray.enable(server, `api-${env}`);
```

**My dynamodb module:**
```javascript
const AWS           = require('./aws');
const AWSXray       = require('aws-xray-sdk');
const dynamoOptions = {
    httpOptions: {
        timeout: 2000
    },
    maxRetries: 0
};

const ddbClient     = AWSXray.captureAWSClient(new AWS.DynamoDB(dynamoOptions));
const dynamoDb      = new AWS.DynamoDB.DocumentClient(dynamoOptions);
dynamoDb.service    = ddbClient;
```

**Comment by awssandra** [comment]
Hi Scandinaro,

We have an open issue with Dynamo Document Client here:
https://github.com/aws/aws-xray-sdk-node/issues/23

Could you verify if the work around fixes your context propagation issue?

Thanks,
Sandra

**Comment by scandinaro** [comment]
@awssandra above I'm using one example from that linked issue solution, and then below I just tried the last suggested solution from @monken, but I'm still receiving the same error.  It seems like maybe this solution works for express, but not restify? 

```javascript
const AWS           = require('./aws');
const AWSXray       = require('aws-xray-sdk');
const dynamoOptions = {
    httpOptions: {
        timeout: 2000
    },
    maxRetries: 0
};

const dynamoDb = new AWS.DynamoDB.DocumentClient({
    service: new AWS.DynamoDB(dynamoOptions)
});

AWSXray.captureAWSClient(dynamoDb.service);
```

**Comment by awssandra** [comment]
That should not be the case. The SDK uses CLS behind the scenes to propagate context, regardless of the framework in use. The context is either getting lost as a part of the Restify hook, or in the AWS call. 

Do any other AWS calls work?
Can you verify if a "xray.getSegment()" call in the route returns the base segment? 
What version of Restify are you using?
Is the "xray.enable(<server>, <name>)" call immediately before your defined routes (after any/all interceptors/hooks)?

**Comment by scandinaro** [comment]
@awssandra just following back up on this.

**Comment by awssandra** [comment]
Hi scandinaro,

Apologies for the delay, much of the team was out for vacation (myself included) and recently back. We're diving into this and will update you as soon as we have more information.

Thanks,
Sandra

**Comment by chrisradek** [comment]
@scandinaro 
I'm trying to reproduce the issue you're seeing but haven't had much luck yet. Here's my full code based on the original example you provided:

__dynamodb.js__
```javascript
const AWS = require('aws-sdk');
const xray = require('aws-xray-sdk');

const options = {
  httpOptions: {
    timeout: 2000
  },
  maxRetries: 0,
  region: 'us-west-2'
};

const client = xray.captureAWSClient(new AWS.DynamoDB(options));
const docClient = new AWS.DynamoDB.DocumentClient(options);
docClient.service = client;

module.exports = {
  client: docClient
};
```
__app.js__
```javascript
const resitfy = require('restify');
const xray = require('aws-xray-sdk-restify');
const client = require('./dynamodb').client;

function createServer() {
  const server = resitfy.createServer({
    name: 'api'
  });

  xray.enable(server, 'restify-root');

  server.use(resitfy.plugins.dateParser());
  server.use(resitfy.plugins.queryParser());
  server.use(resitfy.plugins.bodyParser());

  server.get('/foo', function(req, res, next) {
    client.scan({
      TableName: 'TABLE'
    }, function(err, data) {
      if (err) {
        res.send(err.statusCode, err.message);
        next(err);
      } else {
        res.send(200, data);
        next();
      }
    });
  });

  server.get('/bar', function(req, res, next) {
    client.get({
      TableName: 'TABLE',
      Key: {
        'id': 'ID'
      }
    }, function(err, data) {
      if (err) {
        res.send(err.statusCode, err.message);
        next(err);
      } else {
        data.Item.timestamp = Date.now();
        client.put({
          TableName: 'TABLE',
          Item: data.Item,
          ReturnValues: 'ALL_OLD'
        }, function(err, data) {
          if (err) {
            res.send(err.statusCode, err.message);
            next(err);
          } else {
            res.send(200, data);
            next();
          }
        });
      }
    });
  });

  return server;
}

const server = createServer();

server.listen(3002);
```

Where do you attach your auth middleware? And are you using promises in your routes/middleware? I tried making the `GET /bar` route match your last use case where you get an item, then put an item as a result. Let me know if what you have differs from what I've put together.

**Comment by chrisradek** [comment]
Closing due to inactivity, but feel free to open a new issue if you are still encountering this error.
